# Generated by Django 5.1.4 on 2024-12-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_authority_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='zarinpal_data',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
