# Generated by Django 5.1.4 on 2024-12-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_ref_id_order_zarinpal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zarinpal_data',
            field=models.TextField(blank=True),
        ),
    ]
