# Generated by Django 5.1.4 on 2024-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men shoes', 'Men shoes'), ('Women shoes', 'Women shoes')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
